xm/course_management/urls.py
from django.conf.urls import url

from . import views
urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'getlogin', views.getlogin),
    url(r'xspscj2/(\d+)', views.xspscj2, name='xspscj2'),
    url(r'xskscj2/(\d+)', views.xskscj2, name='xskscj2'),
    url(r'xszpcj2/(\d+)', views.xszpcj2, name='xszpcj2'),
    url(r'xsxkxx2/(\d+)', views.xsxkxx2, name='xsxkxx2'),
    # student
    url(r'xskscj/(\d+)', views.xskscj, name='xskscj'),
    url(r'xspscj/(\d+)', views.xspscj, name='xspscj'),
    url(r'xsxkxx/(\d+)', views.xsxkxx, name='xsxkxx'),
    url(r'xszpcj/(\d+)', views.xszpcj, name='xszpcj'),
    # teacher
    url(r'teach_info/([A-Za-z0-9]+)', views.teach_info, name='teach_info'),
    url(r'stu_info/([A-Za-z0-9]+)', views.stu_info, name='stu_info'),
    url(r'usual_score/([A-Za-z0-9]+)', views.usual_score, name='usual_score'),
    url(r'exam_score/([A-Za-z0-9]+)', views.exam_score, name='exam_score'),
    url(r'score_search/([A-Za-z0-9]+)', views.score_search, name='score_search'),
    url(r'teach_info2/([A-Za-z0-9]+)', views.teach_info2, name='teach_info2'),
    url(r'stu_info2/([A-Za-z0-9]+)', views.stu_info2, name='stu_info2'),
    url(r'usual_score2/([A-Za-z0-9]+)', views.usual_score2, name='usual_score2'),
    url(r'usual_score3/([A-Za-z0-9]+)', views.usual_score3, name='usual_score3'),
    url(r'exam_score2/([A-Za-z0-9]+)', views.exam_score2, name='exam_score2'),
    url(r'exam_score3/([A-Za-z0-9]+)', views.exam_score3, name='exam_score3'),
    url(r'score_search2/([A-Za-z0-9]+)', views.score_search2, name='score_search2'),

]

xm/xm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('course_management.urls', namespace='xm'))
]

xm/templates/teacher/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>欢迎使用课程学习成绩考评系统</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="text/javascript" src="/static/teac_style/js/jquery.js"></script>
	<script type="text/javascript" src="/static/teac_style/js/page_common.js"></script>
    <link href="/static/teac_style/css/common_style_blue.css" rel="stylesheet" type="text/css" />
    <link href="/static/teac_style/css/index_1.css" rel="stylesheet" type="text/css" />
	<link href="/static/teac_style/css/teacher.css" rel="stylesheet" type="text/css" />

	<script type="text/javascript">
		// 显示或隐藏二级菜单 
		function menuClick( menuDiv ){
			$(".MenuLevel2").not( $(menuDiv).next() ).hide();
			$(menuDiv).next().toggle();
		}
		
		$(function(){
			// 默认只显示第1个二级菜单
			$(".MenuLevel2").hide();
			$(".MenuLevel2:first").show();
		});
	</script>

    <style type="text/css">

    html{
    width: 100%;
    }
    body{
        width: 100%;
        background: none repeat scroll 0 0 #D8EDFC;
        margin: 0;
        padding: 0;
    }

    img{
        vertical-align: inherit;
        border:0;
    }
    a { color:#0d71bb; transition:0.5s; }
    a:hover { color:blue; }

    </style>


</head>
<body>
    <div class='top' >
        <!-- 上部 -->
        <div id="Head_1">
            <!-- 标题 -->
            <div id="Head_1_Logo">课程成绩评定系统2.0
                <!-- <img border="0" src="style/images/logo.png" /> -->
            </div>
            <!-- 欢迎用户的文字 -->
            <div id="Head_1_UserWelcome">
                <img border="0" width="13" height="14" src="/static/teac_style/images/user.gif" />
                您好，

                {% block user %}

                {% endblock user%}
            </div>
            <!-- 一些链接按钮 -->
            <div id="Head_1_FunctionButton">
                <!--<a target="right" href="javascript:void(0)">-->
                    <!--<img width="78" height="20" src="/static/teac_style/images/help2.gif" />-->
                <!--</a>-->
                <a href="{% url 'xm:index'%}">
                    <img width="78" height="20" alt="" src="/static/teac_style/images/logout.gif" />
                </a>
            </div>
        </div>
        <!-- 下部 -->
        <div id="Head_2">
            <!-- 任务提醒 -->
            <div id="Head2_Awoke">
                <ul id="AwokeNum">

                </ul>
            </div>

            <div class="Head2_FunctionList" style="float:left">
                <a href="javascript: window.parent.right.history.back();">
                    <img src="/static/teac_style/images/Header_back.gif" width="24" height="24" style="margin-top: -10px;"/>
                    <b>后退</b>
                </a>
                <a href="javascript: window.parent.right.history.forward();">
                    <img src="/static/teac_style/images/Header_forward.gif" width="24" height="24" style="margin-top: -10px;"/>
                    <b>前进</b>
                </a>
            </div>

            <div id="Head2_FunctionList">
                <!--
                    如果使用 window.parent.right.location.reload(true); 则IE与FF都可以使用，Chrome不可以。
                    在Chrome中 alert(window.parent.right.document); 显示的值是 undefined！为什么？
                    使用 window.parent.right.history.go(0) 实现刷新，在IE、Chrome中都可以运行，但在FF中不可以！（但没有测试什么时候会使用缓存）。
                 -->
                <!--<a href="javascript: window.parent.right.history.go(0);">-->
                    <!--<img src="/static/teac_style/images/Header_refresh.gif" width="24" height="24" style="margin-top: -8px;"/>-->
            <!--<b>刷新</b></a></div>-->
            </div>

        </div>
    </div>

    <div class='middle'>
        <div class='left' >
            <ul id="Menu">
            <li class="level1">
                <div onClick="menuClick(this);" class="level1Style">
                    <img src="/static/teac_style/images/func20001.gif" class="Icon" />
                    系统菜单
                </div>
            <ul class="MenuLevel2">
                {% block menu%}
                {% endblock menu%}

                <!--<h2>授课安排</h2>-->
                  <!--<li class="level2 level2Style"> <a target="right" href="course-info.html">授课信息</a></li>-->
                  <!--<li class="level2 level2Style"><a target="right" href="student-info.html">学生情况</a></li>-->
                <!--<h2>成绩管理</h2>-->
                    <!--<li class="level2 level2Style"><a target="right" href="us-score.html">平时成绩</a></li>-->
                    <!--<li class="level2 level2Style"><a target="right" href="exam-score.html">考试成绩</a></li>-->
                <!--<li><a href="select-score.html" target="right"><h2>成绩查询</h2></a></li>-->
            </ul>
            </ul>

        </div>


        <div class='right'>
            {% block mainstu %}

            {% endblock mainstu %}

        </div>
    </div>

    <div class='bottom'>
        <div id="StatusBar">
        <!-- 链接 -->
        <div id="StatusBar_Links">
            <a href="http://www.cuit.edu.cn" target="_blank">成都信息工程大学</a>
        </div>
        <!-- 右侧功能按钮 -->
        <div id="StatusBar_Right">
            <!-- 版本 -->
            <a href="javascript:void(0)">
                <img border="0" width="11" height="11" src="/static/teac_style/images/info.gif" />
                <img border="0" width="40" height="11" src="/static/teac_style/images/version.gif" />
            </a>
        </div>
    </div>
    </div>

</body>
</html>

xm/templates/teacher/course-info.html
{% extends 'teacher/base.html'%}
{% block user %}

<strong>{{teacher.tea_name}}</strong>
{% endblock user %}

{% block menu %}

            <h2>授课安排</h2>
  			  <li class="level2 level2Style"> <a  href="/teach_info/{{teacher.tea_id}}/">授课信息</a></li>
	          <li class="level2 level2Style"><a  href="/stu_info/{{teacher.tea_id}}/">学生情况</a></li>
  			<h2>成绩管理</h2>
               	<li class="level2 level2Style"><a  href="/usual_score/{{teacher.tea_id}}/">平时成绩</a></li>
               	<li class="level2 level2Style"><a  href="/exam_score/{{teacher.tea_id}}/">考试成绩</a></li>
            <h2>成绩查询</h2>
                <li class="level2 level2Style"><a href="/score_search/{{teacher.tea_id}}/">成绩查询</a></li>
{% endblock menu %}


{% block mainstu %}

<!-- 页面标题 -->
<div id="TitleArea">
	<div id="TitleArea_Head"></div>
	<div id="TitleArea_Title">
		<div id="TitleArea_Title_Content">
			<img border="0" width="13" height="13" src="/static/teac_style/images/title_arrow.gif"/> 课程列表
		</div>
    </div>
	<div id="TitleArea_End"></div>
</div>


<!-- 过滤条件 -->
<div id="QueryArea">
	<form action="/teach_info2/{{teacher.tea_id}}/" method="get">
		<!--<input type="hidden" name="method" value="search">-->
		<input type="text" name="cname" placeholder="请输入课程名称">
        <select  name="seme" id="seme">
        <option>请选择学期</option><!--这里要从数据库提取，但我们不会用ajax-->
            {% for seme in semester%}
            <option>{{seme}}</option>
            {%endfor%}
        </select>
        <select  name="class" id="class">
        <option>请选择班级</option><!--这里要从数据库提取，但我们不会用ajax-->
            {%for class in classes%}
            <option>{{class}}</option>
            {%endfor%}
        </select>
		<input type="submit" value="搜索">
	</form>
</div>


<!-- 主内容区域（数据列表或表单显示） -->
<div id="MainArea">
    <table class="MainArea_Content" cellspacing="0" cellpadding="0">
        <!-- 表头-->
        <thead>
            <tr align="center" valign="middle" id="TableTitle">
				<td>课程名称</td>
				<td>教学班</td>
				<td>教学形式</td>
				<td>考试类别</td>
				<td>总学时</td>
                <td>讲授学时</td>
                <td>实验学时</td>
                <td>实习学时</td>
                <td>上机学时</td>
                <!--<td>分值比例</td>-->
                <td>主管单位</td>
                <td>适用学期</td>
			</tr>
		</thead>
        <!--显示数据列表 -->
        <tbody id="TableData" align="center">
            {% for course in course_info %}
			<tr class="TableDetail1" >
				<td>{{course.sel_cour_name}}&nbsp;</td>
				<td>{{course.stu_class}}&nbsp;</td>
				<td>{{course.tea_mode}}&nbsp;</td>
				<td>{{course.tes_category}}&nbsp;</td>
                <td>{{course.total_hours}}&nbsp;</td>
				<td>{{course.teach}}&nbsp;</td>
                <td>{{course.experiment}}&nbsp;</td>
                <td>{{course.practise}}&nbsp;</td>
                <td>{{course.operate}}&nbsp;</td>
                <td>{{course.department}}&nbsp;</td>
                <td>{{course.semester}}&nbsp;</td>
			</tr>
            {% endfor %}

        </tbody>
    </table>
</div>

{% endblock mainstu%}

xm/templates/teacher/exam-score.html
{% extends 'teacher/base.html'%}

{% block user %}

<strong>{{teacher.tea_name}}</strong>
{% endblock user %}

{% block menu %}

            <h2>授课安排</h2>
  			  <li class="level2 level2Style"> <a  href="/teach_info/{{teacher.tea_id}}/">授课信息</a></li>
	          <li class="level2 level2Style"><a  href="/stu_info/{{teacher.tea_id}}/">学生情况</a></li>
  			<h2>成绩管理</h2>
               	<li class="level2 level2Style"><a  href="/usual_score/{{teacher.tea_id}}/">平时成绩</a></li>
               	<li class="level2 level2Style"><a  href="/exam_score/{{teacher.tea_id}}/">考试成绩</a></li>
            <h2>成绩查询</h2>
                <li class="level2 level2Style"><a href="/score_search/{{teacher.tea_id}}/">成绩查询</a></li>
{% endblock menu %}


{% block mainstu %}

<!-- 页面标题 -->
	<div id="TitleArea">
		<div id="TitleArea_Head"></div>
		<div id="TitleArea_Title">
			<div id="TitleArea_Title_Content">
				<img border="0" width="13" height="13"
					src="/static/teac_style/images/title_arrow.gif" /> 考试成绩信息
			</div>
		</div>
		<div id="TitleArea_End"></div>
	</div>

	<!-- 主内容区域（数据列表或表单显示） -->
    <div id="QueryArea">
	<form action="/exam_score2/{{teacher.tea_id}}/" method="get">
		<input type="hidden" name="method" value="search">
        <select  name="cname" id="cname">
        <option>请选择授课名称</option><!--这里要从数据库提取，但我们不会用ajax-->
        {% for name in names%}
            <option>{{name}}</option>
            {%endfor%}
		</select>
		<input type="submit" value="搜索">
	</form>
</div>

    <form action="/exam_score3/{{teacher.tea_id}}/" method="get">
	<div id="MainArea">
		<table class="MainArea_Content" align="center" cellspacing="0" cellpadding="0">
			<!-- 表头-->
			<thead>
				<tr align="center" valign="middle" id="TableTitle">
					<td>学号</td>
                    <td >姓名</td>
					<td >专业</td>
					<td >课程名称</td>
					<td>第一大题</td>
					<td>第二大题</td>
                    <td>第三大题</td>
                    <td>第四大题</td>
				</tr>
			</thead>
			<!--显示数据列表 -->
			 <tbody id="TableData">
            {%for stu in allstu%}
			<tr class="TableDetail1">

				<td align="center"><input value="{{stu.stu_id}}" name="id" style="border: 0" readonly/></td>
				<td align="center"><input value="{{stu.stu_name}}"  style="border: 0" readonly/></td>
				<td align="center"><input value="{{stu.stu_major}}"  style="border: 0" readonly/></td>
				<td align="center"><input value="{{stu.sel_cour_name}}" name="name" style="border: 0" readonly/></td>

                <td align="center"><input name="one" type="text"/></td>
                <td align="center"><input name="two" type="text"/></td>
                <td align="center"><input name="three" type="text"/></td>
                <td align="center"><input name="four" type="text"/></td>
                </tr>
            {%endfor%}
                </tbody>


		</table>
		<!-- 其他功能超链接 -->
		<div id="TableTail" align="center">
        <input type="submit" value="提交"/>
		</div>
	</div>
    </form>
{% endblock mainstu%}

xm/templates/teacher/select-score.html
{% extends 'teacher/base.html'%}

{% block user %}

<strong>{{teacher.tea_name}}</strong>
{% endblock user %}

{% block menu %}

            <h2>授课安排</h2>
  			  <li class="level2 level2Style"> <a  href="/teach_info/{{teacher.tea_id}}/">授课信息</a></li>
	          <li class="level2 level2Style"><a  href="/stu_info/{{teacher.tea_id}}/">学生情况</a></li>
  			<h2>成绩管理</h2>
               	<li class="level2 level2Style"><a  href="/usual_score/{{teacher.tea_id}}/">平时成绩</a></li>
               	<li class="level2 level2Style"><a  href="/exam_score/{{teacher.tea_id}}/">考试成绩</a></li>
            <h2>成绩查询</h2>
                <li class="level2 level2Style"><a href="/score_search/{{teacher.tea_id}}/">成绩查询</a></li>
{% endblock menu %}


{% block mainstu %}

<!-- 页面标题 -->
	<div id="TitleArea">
		<div id="TitleArea_Head"></div>
		<div id="TitleArea_Title">
			<div id="TitleArea_Title_Content">
				<img border="0" width="13" height="13"
					src="/static/teac_style/images/title_arrow.gif" /> 总成绩表
			</div>
		</div>
		<div id="TitleArea_End"></div>
	</div>

	<!-- 主内容区域（数据列表或表单显示） -->
    <div id="QueryArea">
	<form action="/score_search2/{{teacher.tea_id}}/" method="get">
		<input type="hidden" name="method" value="search">
        <select  name="cname" id="cname">
        <option>请选择授课名称</option><!--这里要从数据库提取，但我们不会用ajax-->
			{% for name in names%}
            <option>{{name}}</option>
            {%endfor%}
        </select>
        <select  name="class" id="class">
        <option>请选择授课班级</option><!--这里要从数据库提取，但我们不会用ajax-->
            {%for class in classes%}
            <option>{{class}}</option>
            {%endfor%}
        </select>
		<input type="submit" value="搜索">
	</form>
</div>
	<div id="MainArea">
		<table class="MainArea_Content" align="center" cellspacing="0" cellpadding="0">
			<!-- 表头-->
			<thead>
				<tr align="center" valign="middle" id="TableTitle">
					<td>学号</td>
                    <td>姓名</td>
					<td>专业</td>
                    <td>年级</td>
					<td >课程名称</td>
                    <td>平时成绩</td>
                    <td>考试成绩</td>
                    <td>总评成绩</td>
			  </tr>
			</thead>
			<!--显示数据列表 -->
			<tbody id="TableData">
            {%for stu in allstu%}
			<tr class="TableDetail1">
				<td>{{stu.stu_id}}</td>
				<td>{{stu.stu_name}}</td>
				<td>{{stu.stu_major}}</td>
			  	<td>{{stu.stu_grade}}</td>
                <td>{{stu.sel_cour_name}}</td>
                <td>{{stu.us_scor}}</td>
                <td>{{stu.exam_score}}</td>
                <td>{{stu.tota_score}}</td>
			 	<td>
                </td>
            {%endfor%}
			</tbody>
		</table>
		<!-- 其他功能超链接 -->
		<div id="TableTail" align="center">
		</div>
	</div>

{% endblock mainstu %}

xm/templates/teacher/student-info.html
{% extends 'teacher/base.html'%}

{% block user %}

<strong>{{teacher.tea_name}}</strong>
{% endblock user %}

{% block menu %}

            <h2>授课安排</h2>
  			  <li class="level2 level2Style"> <a  href="/teach_info/{{teacher.tea_id}}/">授课信息</a></li>
	          <li class="level2 level2Style"><a  href="/stu_info/{{teacher.tea_id}}/">学生情况</a></li>
  			<h2>成绩管理</h2>
               	<li class="level2 level2Style"><a  href="/usual_score/{{teacher.tea_id}}/">平时成绩</a></li>
               	<li class="level2 level2Style"><a  href="/exam_score/{{teacher.tea_id}}/">考试成绩</a></li>
            <h2>成绩查询</h2>
                <li class="level2 level2Style"><a href="/score_search/{{teacher.tea_id}}/">成绩查询</a></li>
{% endblock menu %}


{% block mainstu %}

<!-- 页面标题 -->
	<div id="TitleArea">
		<div id="TitleArea_Head"></div>
		<div id="TitleArea_Title">
			<div id="TitleArea_Title_Content">
				<img border="0" width="13" height="13"
					src="/static/teac_style/images/title_arrow.gif" /> 学生名单
			</div>
		</div>
		<div id="TitleArea_End"></div>
	</div>
	<!-- 过滤条件 -->
	<div id="QueryArea">
		<form action="/stu_info2/{{teacher.tea_id}}/" method="get">
			<!--<input type="hidden" name="method" value="search">-->
			<!--<input type="text" name="cname" placeholder="请输入课程名称">-->
            <select  name="cname" id="cname">
            <option>请选择课程</option><!--这里要从数据库提取，但我们不会用ajax-->
            {% for name in names%}
            <option>{{name}}</option>
            {%endfor%}
            </select>
            <select  name="seme" id="seme">
            <option>请选择学期</option><!--这里要从数据库提取，但我们不会用ajax-->
            {% for seme in semester%}
            <option>{{seme}}</option>
            {%endfor%}
            </select>
            <select  name="class" id="class">
            <option>请选择班级</option><!--这里要从数据库提取，但我们不会用ajax-->
				{%for class in classes%}
            <option>{{class}}</option>
            {%endfor%}
            </select>
			<input type="submit" value="搜索">
		</form>
	</div>

	<!-- 主内容区域（数据列表或表单显示） -->
	<div id="MainArea">
		<table width="30%" align="center" cellpadding="0" cellspacing="0" class="MainArea_Content">
			<!-- 表头-->
<thead>
				<tr align="center" valign="middle" id="TableTitle">
					<td width="16%">学号</td>
				  		<td>姓名</td>
	  </tr>
			</thead>
			<!--显示数据列表 -->
			<tbody id="TableData">
            {% for stu in students %}
			<tr class="TableDetail1" >
				<td>{{stu.stu_id}}&nbsp;</td>
				<td>{{stu.stu_name}}&nbsp;</td>

			</tr>
            {% endfor %}



			</tbody>
		</table>
</div>

{% endblock mainstu%}

xm/templates/teacher/teach_home.html
{% extends 'teacher/base.html'%}

{% block user %}

<strong>{{teacher.tea_name}}</strong>
{% endblock user %}

{% block menu %}

            <h2>授课安排</h2>
  			  <li class="level2 level2Style"> <a  href="/teach_info/{{teacher.tea_id}}/">授课信息</a></li>
	          <li class="level2 level2Style"><a  href="/stu_info/{{teacher.tea_id}}/">学生情况</a></li>
  			<h2>成绩管理</h2>
               	<li class="level2 level2Style"><a  href="/usual_score/{{teacher.tea_id}}/">平时成绩</a></li>
               	<li class="level2 level2Style"><a  href="/exam_score/{{teacher.tea_id}}/">考试成绩</a></li>
            <h2>成绩查询</h2>
                <li class="level2 level2Style"><a href="/score_search/{{teacher.tea_id}}/">成绩查询</a></li>
{% endblock menu %}


{% block mainstu %}

<h1 align="center">欢迎使用课程学习成绩考评系统</h1>

{% endblock mainstu%}

xm/templates/teacher/updatescore.html
{% extends 'teacher/base.html'%}

{% block user %}

<strong>{{teacher.tea_name}}</strong>
{% endblock user %}

{% block menu %}

            <h2>授课安排</h2>
  			  <li class="level2 level2Style"> <a  href="/teach_info/{{teacher.tea_id}}/">授课信息</a></li>
	          <li class="level2 level2Style"><a  href="/stu_info/{{teacher.tea_id}}/">学生情况</a></li>
  			<h2>成绩管理</h2>
               	<li class="level2 level2Style"><a  href="/usual_score/{{teacher.tea_id}}/">平时成绩</a></li>
               	<li class="level2 level2Style"><a  href="/exam_score/{{teacher.tea_id}}/">考试成绩</a></li>
            <h2>成绩查询</h2>
                <li class="level2 level2Style"><a href="/score_search/{{teacher.tea_id}}/">成绩查询</a></li>
{% endblock menu %}


{% block mainstu %}

<!-- 页面标题 -->
<div id="TitleArea">
	<div id="TitleArea_Head"></div>
	<div id="TitleArea_Title">
		<div id="TitleArea_Title_Content">


					<img border="0" width="13" height="13" src="/static/teac_style/images/title_arrow.gif"/> 修改成绩



		</div>
    </div>
	<div id="TitleArea_End"></div>
</div>


<!-- 主内容区域（数据列表或表单显示） -->
<div id="MainArea">
	<!-- 表单内容 -->
	<form action="#" method="post">

		<!-- 本段标题（分段标题） -->
		<div class="ItemBlock_Title">
        	<img width="4" height="7" border="0" src="/static/teac_style/images/item_point.gif"> 成绩信息&nbsp;
        </div>
		<!-- 本段表单字段 -->
        <div class="ItemBlockBorder">
            <div class="ItemBlock">
				<div class="ItemBlock2">
					<table cellpadding="0" cellspacing="0" class="mainForm">
						<thead>
						<tr align="center" valign="middle" id="TableTitle">
                            <td>学号</td>
                            <td>姓名</td>
                            <td>专业</td>
                            <td>年级</td>
                            <td>平时成绩</td>
                            <td>考试成绩</td>
                            <td>总评成绩</td>
			  			</tr>
						</thead>

		<tbody id="TableData">

			<tr class="TableDetail1">
				<td>2015215001</td>
				<td>刘天宇</td>
				<td>信息管理与信息系统</td>
			  	<td>2015</td>
				<td align="center"><input type="text"/>
                <td align="center"><input type="text"/>
                <td></td>
               </table>
				</div>
            </div>
        </div>
		<!-- 表单操作 -->
		<div id="InputDetailBar">


					 <input type="submit" value="提交" class="FunctionButtonInput">



            <a href="javascript:history.go(-1);" class="FunctionButton">返回</a>
        </div>
	</form>

</div>


{% endblock mainstu%}

xm/templates/teacher/us-score.html
{% extends 'teacher/base.html'%}

{% block user %}

<strong>{{teacher.tea_name}}</strong>
{% endblock user %}

{% block menu %}

            <h2>授课安排</h2>
  			  <li class="level2 level2Style"> <a  href="/teach_info/{{teacher.tea_id}}/">授课信息</a></li>
	          <li class="level2 level2Style"><a  href="/stu_info/{{teacher.tea_id}}/">学生情况</a></li>
  			<h2>成绩管理</h2>
               	<li class="level2 level2Style"><a  href="/usual_score/{{teacher.tea_id}}/">平时成绩</a></li>
               	<li class="level2 level2Style"><a  href="/exam_score/{{teacher.tea_id}}/">考试成绩</a></li>
            <h2>成绩查询</h2>
                <li class="level2 level2Style"><a href="/score_search/{{teacher.tea_id}}/">成绩查询</a></li>
{% endblock menu %}


{% block mainstu %}

    <!-- 页面标题 -->
<div id="TitleArea">
		<div id="TitleArea_Head"></div>
		<div id="TitleArea_Title">
			<div id="TitleArea_Title_Content">
				<img border="0" width="13" height="13"
					src="/static/teac_style/images/title_arrow.gif" /> 学生表
			</div>
		</div>
		<div id="TitleArea_End"></div>
</div>

	<!-- 主内容区域（数据列表或表单显示） -->
<div id="QueryArea">
	<form action="/usual_score2/{{teacher.tea_id}}/" method="get">
		<input type="hidden" name="method" value="search">
        <select  name="cname" id="cname">
        <option>请选择授课名称</option><!--这里要从数据库提取，但我们不会用ajax-->
			{% for name in names%}
            <option>{{name}}</option>
            {%endfor%}
        </select>
		<input type="submit" value="搜索">
	</form>
</div>
<form action="/usual_score3/{{teacher.tea_id}}/" method="get">
<div id="MainArea">

		<table class="MainArea_Content" align="center" cellspacing="0" cellpadding="0">
			<!-- 表头-->
			<thead>
				<tr align="center" valign="middle" id="TableTitle">
					<td>学号</td>
                    <td >姓名</td>
					<td >专业</td>
					<td >课程名称</td>
                    <td >考勤</td>
					<td >实验</td>
					<td >作业</td>
                    <td >课堂表现</td>
				</tr>
			</thead>
			<!--显示数据列表 -->
			 <tbody id="TableData">
            {%for stu in allstu%}

			<tr  class="TableDetail1">

                <td align="center"><input value="{{stu.stu_id}}" name="id" style="border: 0" readonly/></td>
				<td align="center"><input value="{{stu.stu_name}}"  style="border: 0" readonly/></td>
				<td align="center"><input value="{{stu.stu_major}}"  style="border: 0" readonly/></td>
				<td align="center"><input value="{{stu.sel_cour_name}}" name="name" style="border: 0" readonly/></td>

                <td align="center"><input name="one" type="text"/></td>
                <td align="center"><input name="two" type="text"/></td>
                <td align="center"><input name="three" type="text"/></td>
                <td align="center"><input name="four" type="text"/></td>
                </tr>

             {%endfor%}
                </tbody>

		</table>

		<!-- 其他功能超链接 -->
		<div id="TableTail" align="center">
        <input type="submit" value="提交" />
		</div>

</div>
</form>
{% endblock mainstu %}